= BeagleBone Black Community BSP

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo
$: PATH=${PATH}:~/bin

Download the BSP source:

[source,console]
$: mkdir bbb-community-bsp
$: cd bbb-community-bsp
$: repo init -u https://github.com/geoffrey-vl/bbb-community-bsp-platform -b mbed-pelion
$: repo sync

At the end of the commands you have every metadata you need to start work with.
The source code is checked out at `bbb-community-bsp/sources`.
You can use any directory to host your build.
As a personal favor I'm using `bbb-community-bsp/build` as build folder.

To configure the build:

[source,console]
$: chmod a+x .repo/manifests/setup.sh
$: .repo/manifests/setup.sh

Afterwards you may want to edit the build/conf/local.conf to set the correct machine.
Also make sure to either update the *MBED_CLOUD_IDENTITY_CERT_FILE* variable inside build/conf/local.conf or make sure to copy the certificate into the build/conf folder.

To start a simple image build:

[source,console]
$: source sources/poky/oe-init-build-env build
$: bitbake mbed-cloud-client-example-nofwup-image.bb

Other images:

* basic-image
* bluetooth-image
* can-console-image
* console-image
* installer-image
* iot-image
* qt5-image
* qt5-x11-image
* usbproxy-image
* x11-image
* mbed-cloud-console-image
* mbed-cloud-client-example-nofwup-image.bb
* mbed-cloud-client-example-image

To create an sd card:

[source,console]
$: chmod a+x .repo/manifests/write2sd.sh
$: .repo/manifests/write2sd.sh

More documentation at http://www.jumpnowtek.com/rpi/BeagleBone-Systems-with-Yocto.html
